server.port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /data-api
books:
  page-size: 10

---
spring:
  datasource:
    url: 'jdbc:h2:file:./h2-db/bookstore'
    name: bookstore
    username: sa
    password: '123'
    generate-unique-name: false
  config:
    activate:
      on-profile: prod

server.port: 8081